export type MenuItemRecord = {
  id: number;
  name: string;
  description: string;
  category: string;
  price: number;
  emoji: string;
  popular: boolean;
  available: boolean;
  sortOrder: number;
};

export const DEFAULT_MENU_ITEMS: MenuItemRecord[] = [
  {
    id: 1,
    name: "Espresso",
    description: "Yoğun, aromatik ve keskin bir kahve.",
    category: "Sıcak Kahveler",
    price: 6500,
    emoji: "☕",
    popular: false,
    available: true,
    sortOrder: 1,
  },
  {
    id: 2,
    name: "Double Espresso",
    description: "Enerjiye ihtiyaç duyanlara ekstra yoğunluk.",
    category: "Sıcak Kahveler",
    price: 8000,
    emoji: "☕",
    popular: false,
    available: true,
    sortOrder: 2,
  },
  {
    id: 3,
    name: "Americano",
    description: "Espresso üzerine sıcak su; hafif ama karakterli.",
    category: "Sıcak Kahveler",
    price: 7000,
    emoji: "☕",
    popular: false,
    available: true,
    sortOrder: 3,
  },
  {
    id: 4,
    name: "Latte",
    description: "Espresso ve süt kremasının mükemmel dengesi.",
    category: "Sıcak Kahveler",
    price: 8500,
    emoji: "🥛",
    popular: true,
    available: true,
    sortOrder: 4,
  },
  {
    id: 5,
    name: "Cappuccino",
    description: "Bol süt köpüğüyle kahve severlerin vazgeçilmezi.",
    category: "Sıcak Kahveler",
    price: 8500,
    emoji: "☕",
    popular: false,
    available: true,
    sortOrder: 5,
  },
  {
    id: 6,
    name: "Flat White",
    description: "Yoğun espresso ve kadifemsi sütün güçlü uyumu.",
    category: "Sıcak Kahveler",
    price: 9000,
    emoji: "🥛",
    popular: false,
    available: true,
    sortOrder: 6,
  },
  {
    id: 7,
    name: "Mocha",
    description: "Kahve, süt ve çikolatanın tatlı uyumu.",
    category: "Sıcak Kahveler",
    price: 9500,
    emoji: "🍫",
    popular: false,
    available: true,
    sortOrder: 7,
  },
  {
    id: 8,
    name: "Cold Brew",
    description: "16 saat demlenen, yumuşak içimli ve ferahlatıcı.",
    category: "Soğuk Kahveler",
    price: 9500,
    emoji: "🧊",
    popular: true,
    available: true,
    sortOrder: 8,
  },
  {
    id: 9,
    name: "Iced Americano",
    description: "Klasik Amerikan kahvesinin buzla buluşmuş serin hali.",
    category: "Soğuk Kahveler",
    price: 8000,
    emoji: "🧊",
    popular: false,
    available: true,
    sortOrder: 9,
  },
  {
    id: 10,
    name: "Iced Latte",
    description: "Soğuk süt ve buzla hafif ama doyurucu.",
    category: "Soğuk Kahveler",
    price: 9000,
    emoji: "🥛",
    popular: false,
    available: true,
    sortOrder: 10,
  },
  {
    id: 11,
    name: "Espresso Tonic",
    description: "Tonik ve espressonun sıra dışı ferahlığı.",
    category: "Soğuk Kahveler",
    price: 9500,
    emoji: "🍹",
    popular: false,
    available: true,
    sortOrder: 11,
  },
  {
    id: 12,
    name: "Matcha Latte",
    description: "Antioksidan dolu Japon yeşil çayı ve süt.",
    category: "Özel İçecekler",
    price: 10000,
    emoji: "🍵",
    popular: true,
    available: true,
    sortOrder: 12,
  },
  {
    id: 13,
    name: "Golden Milk",
    description: "Zerdeçal, tarçın, süt ve balın sıcak buluşması.",
    category: "Özel İçecekler",
    price: 9500,
    emoji: "🌙",
    popular: false,
    available: true,
    sortOrder: 13,
  },
  {
    id: 14,
    name: "Chai Latte",
    description: "Baharat karışımıyla zenginleştirilmiş sütlü çay.",
    category: "Özel İçecekler",
    price: 9000,
    emoji: "🫖",
    popular: false,
    available: true,
    sortOrder: 14,
  },
  {
    id: 15,
    name: "Kruvasan Sade",
    description: "Tereyağlı Fransız hamur işi; kahveyle mükemmel uyum.",
    category: "Tatlılar",
    price: 6500,
    emoji: "🥐",
    popular: false,
    available: true,
    sortOrder: 15,
  },
  {
    id: 16,
    name: "Kruvasan Çikolatalı",
    description: "Tereyağlı kruvasan ve yoğun çikolata dolgusu.",
    category: "Tatlılar",
    price: 7500,
    emoji: "🥐",
    popular: false,
    available: true,
    sortOrder: 16,
  },
  {
    id: 17,
    name: "Brownie",
    description: "Yoğun çikolata ve hafif nemli dokusuyla enerji dolu.",
    category: "Tatlılar",
    price: 8000,
    emoji: "🍫",
    popular: false,
    available: true,
    sortOrder: 17,
  },
  {
    id: 18,
    name: "Cheesecake",
    description: "Kremamsı hafifliğiyle klasik bir lezzet.",
    category: "Tatlılar",
    price: 9000,
    emoji: "🍰",
    popular: true,
    available: true,
    sortOrder: 18,
  },
  {
    id: 19,
    name: "Granola Bowl",
    description: "Yoğurt, granola ve mevsim meyveleriyle sağlıklı seçim.",
    category: "Tatlılar",
    price: 9500,
    emoji: "🥣",
    popular: false,
    available: true,
    sortOrder: 19,
  },
];
